window.ticker = window.ticker || {}

/*All values has to be uniq*/

ticker.vavilon = "Vavilon"
ticker["7dicks_soup"] = "7-dicks soup"
ticker.dick = "Dick"
ticker.water = "Water"

ticker.ak74 = "AK 74"
ticker.ak74_black = "AK 74 Black"
ticker.arbalet = "Arbalet"
ticker.awp = "AWP"
ticker.awp_black = "AWP Black"
ticker.axe = "Axe"
ticker.beretta = "Beretta"
ticker.bizon = "Bizon"
ticker.deagle = "Deagle"
ticker.famas = "FAMAS"
ticker.flash = "Flash"
ticker.galil = "Galil"
ticker.granate = "Granate"
ticker.granate_launcher = "Granate Launcher"
ticker.iron_ingot = "Iron Ingot"
ticker.knife = "Knife"
ticker.laser = "Laser"
ticker.m16 = "M16"
ticker.magnum = "Magnum"
ticker.minigun = "Minigun"
ticker.mp5 = "MP5"
ticker.p90 = "P90"
ticker.revolver = "Revolver"
ticker.rifle = "Rifle"
ticker.rpg = "RPG"
ticker.ruger = "Ruger"
ticker.scar = "SCAR"
ticker.smoke = "Smoke"
ticker.svd = "SVD"
ticker.sword = "Sword"
ticker.ump45 = "UMP45"
ticker.uzi = "UZI"
ticker.xm1014 = "XM1014"
ticker.zeus = "Zeus"
