window.ticker = window.ticker || {}

/*Все значения должны быть уникальными*/

ticker.vavilon = "Вавилон"
ticker["7dicks_soup"] = "Суп из 7-хуёв"
ticker.dick = "Хуй"
ticker.water = "Вода"

ticker.ak74 = "АК-74"
ticker.ak74_black = "АК-74 Чёрный"
ticker.arbalet = "Арбалет"
ticker.awp = "AWP"
ticker.awp_black = "AWP Чёрная"
ticker.axe = "Топор"
ticker.beretta = "Беретта"
ticker.bizon = "Бизон"
ticker.deagle = "Deagle"
ticker.famas = "FAMAS"
ticker.flash = "Светошумовая"
ticker.galil = "Galil"
ticker.granate = "Граната"
ticker.granate_launcher = "Гранатомёт"
ticker.iron_ingot = "Железный слиток"
ticker.knife = "Нож"
ticker.laser = "Лазер"
ticker.m16 = "М16"
ticker.magnum = "Магнум"
ticker.minigun = "Миниган"
ticker.mp5 = "MP5"
ticker.p90 = "P90"
ticker.revolver = "Револьвер"
ticker.rifle = "Винтовка"
ticker.rpg = "РПГ"
ticker.ruger = "Ругер"
ticker.scar = "SCAR"
ticker.smoke = "Дымовая"
ticker.svd = "СВД"
ticker.sword = "Меч"
ticker.ump45 = "UMP45"
ticker.uzi = "Узи"
ticker.xm1014 = "XM1014"
ticker.zeus = "Зевс"