window.str = {
    ...window.str,
    wallet: "Wallet",
    history: "History",
    home: "Home",
    there_is_no_history_yet: "There is no history yet",
    M: "M",
    H: "H",
    D: "D",
    W: "W",
    funnel: "Funnel",
    please_leave_feedback: "Please leave feedback",
    reviews: "Reviews",
    you_can_get_credit: "You can get credit",
    total: "Total",
    percent: "Percent",
    credit_rules: "Credit Rules",
    agree_to: "Agree to",
    accept: "Accept",
    decline: "Decline",
    deposit: "Deposit",
    tron_address: "TRON Address (TRC-20)",
    copy: "Copy",
    deposit_deadline: "Deposit Deadline",
    deposit_check: "Deposit Check",
    amount: "Amount",
    commission: "Commission",
    withdrawal: "Withdrawal",
    orders: "Orders",
    filled: "Filled",
    there_is_no_orders_yet: "There are no orders yet",
    mining: "Mining",
    last_reward: "Last Reward",
    in_bank: "In Bank",
    difficulty: "Difficulty",
    start: "Start",
    stop: "Stop",
    skip: "Skip",
    success: "Success",
    close: "Close",
    top_mining: "Top Mining",
    top_exchange: "Top Exchange",
    sent: "Sent",
    received: "Received",
    from: "From",
    to: "To",
    status: "Status",
    competed: "Competed",
    time: "Time",
    welcome: "Welcome to MFM Wallet",
    welcome_subject: "Here you can create your own token.",
    login_or_create_account: "Login or Create Account",
    receive: "Receive",
    scan: "Scan",
    send: "Send",
    credit: "Credit",
    launch_token: "Launch Token",
    logo: "Logo",
    upload_logo: "Upload Logo",
    save: "Save",
    new_token: "New Token",
    token_name: "Token Name",
    min_3_symbols: "Minimum 3 symbols",
    terms_and_conditions: "Terms and Conditions",
    login: "Login",
    username: "Username",
    password: "Password",
    staking: "Staking",
    exchange: "Exchange",
    tokenomics: "Tokenomics",
    total_sypply: "Total Supply",
    circulation_supply: "Circulation Supply",
    distribution: "Distribution",
    created: "Created",
    activity: "Activity",
    volume: "Volume",
    accounts: "Accounts",
    transactions: "Transactions",
    network: "Network",
    all_tokens: "All Tokens",
    all_accounts: "All Accounts",
    all_transactions: "All Transactions",
    sell: "Sell",
    buy: "Buy",
    search: "Search",
    settings: "Settings",
    leave_review: "Leave a Review",
    logout: "Logout",
    admin_panel: "Admin Panel",
    details: "Details",
    second: "Second",
    seconds: "Seconds",
    minute: "Minute",
    minutes: "Minutes",
    hour: "Hour",
    hours: "Hours",
    day: "Day",
    days: "Days",
    month: "Month",
    months: "Months",
    week: "Week",
    weeks: "Weeks",
    year: "Year",
    years: "Years",
    ago: "Ago",
    today: "Today",
    type_token_name: "Type token name",
    language: "Language",
    help: "Help",
};
