window.str = window.str || {}

str.nothing_found = "Nothing found"
str.invite_friend = "Invite friend"
str.referral_link = "Referral link"
str.craft = "Craft"
str.decraft = "Decraft"
str.contracts = "Contracts"
str.simple_token = "Simple token"
str.mining_token = "Mining token"
str.craft_token = "Craft token"
str.recipe = "Recipe"
str.transactions_only_by_request = "Translations only by request"
str.friends_invited = "Friends invited"
str.shops = "Shops"

str.assault_rifles = "Assault rifles"
str.sniper_rifles = "Sniper rifles"
str.smgs = "Smgs"
str.pistols = "Pistols"
str.heavy_weapons = "Heavy weapons"
str.melee = "Melee"
str.grenades = "Grenades"
str.specials = "Specials"
str.open_loader = "Open loader"