window.str = window.str || {}

str.nothing_found = "Ничего не найдено"
str.invite_friend = "Пригласить друга"
str.referral_link = "Ссылка для приглашения"
str.craft = "Создать"
str.decraft = "Разобрать"
str.contracts = "Контракты"
str.simple_token = "Простой токен"
str.mining_token = "Токен добычи"
str.craft_token = "Токен создания"
str.recipe = "Рецепт"
str.transactions_only_by_request = "Переводы только по запросу"
str.friends_invited = "Приглашенные друзья"
str.shops = "Магазины"

str.assault_rifles = "Автоматические винтовки"
str.sniper_rifles = "Снайперские винтовки"
str.smgs = "Пистолетные автоматы"
str.pistols = "Пистолеты"
str.heavy_weapons = "Тяжёлое оружие"
str.melee = "Ближний бой"
str.grenades = "Гранаты"
str.specials = "Спец. оружие"
str.open_loader = "Открыть загрузчик"
str.epoch = "Эпоха"
str.will_end_in = "Закончится через"
str.week = "Неделя"